apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: "trial22aca5.jfrog.io/docker-local/demo-app"
    argocd-image-updater.argoproj.io/demo-app.update-strategy: "latest"
    argocd-image-updater.argoproj.io/write-back-method: "git:secret"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-container
          image: trial22aca5.jfrog.io/docker-local/demo-app:latest
          ports:
            - containerPort: 8080
