name: Update K8s Image for my-app

on:
  repository_dispatch:
    types: [update-image]

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Extract and Validate Payload
        run: |
          echo "Received Payload:"
          echo '${{ toJson(github.event) }}'

          REPO_PATH="${{ github.event.client_payload.repository.name }}"
          NEW_TAG="${{ github.event.client_payload.tag }}"
          FILE_PATH="deployment.yaml"

          IMAGE_NAME=$(echo "$REPO_PATH" | cut -d'/' -f1)

          if [[ "$IMAGE_NAME" != "my-app" ]]; then
            echo "Skipping update. Image '${IMAGE_NAME}' is not 'my-app'."
            exit 0
          fi

          echo "Updating deployment for 'my-app' with tag: $NEW_TAG"

          yq -y -i '.spec.template.spec.containers[0].image = "'"${IMAGE_NAME}:${NEW_TAG}"'"' $FILE_PATH

      - name: Configure Git for Unsigned Commits
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global commit.gpgsign false
          git config --global gpg.program ""

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.ATLAS_GITHUB_PAT }}
        run: |
          set -e

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Use PAT for authentication
          REPO_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"

          git add deployment.yaml

          if git diff --cached --quiet; then
            echo "✅ No changes detected. Skipping commit."
            exit 0
          fi

          git commit -m "feat: update my-app image to $NEW_TAG"

          echo "🚀 Pushing changes to the main branch..."
          git push "$REPO_URL" HEAD:main
