name: Update K8s Image for my-app

on:
  repository_dispatch:
    types: [update-image]

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Extract and Validate Payload
        run: |
          # Debugging payload to verify structure
          echo "Received Payload:"
          echo '${{ toJson(github.event) }}'

          # Extract repository path and tag from the payload
          REPO_PATH="${{ github.event.client_payload.repository.name }}"
          NEW_TAG="${{ github.event.client_payload.tag }}"
          FILE_PATH="deployment.yaml"

          # Extract image name from the repository path (extracts 'my-app' from 'my-app/v1.0.7/manifest.json')
          IMAGE_NAME=$(echo "$REPO_PATH" | cut -d'/' -f1)

          # Ensure this workflow runs only for 'my-app'
          if [[ "$IMAGE_NAME" != "my-app" ]]; then
            echo "Skipping update. Image '${IMAGE_NAME}' is not 'my-app'."
            exit 0
          fi

          echo "Updating deployment for 'my-app' with tag: $NEW_TAG"

          # Update the image tag in deployment.yaml
          yq e -i '.spec.template.spec.containers[] |=
            select(.image | test("'"${IMAGE_NAME}"'")) |
            .image = "'"${IMAGE_NAME}:${NEW_TAG}"'"' $FILE_PATH

      - name: Commit and Push Changes
        if: success()  # Only runs if 'my-app' was detected
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add deployment.yaml
          git commit -m "Update my-app image to $NEW_TAG"
          git push
